/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tarea01.hdg;

import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author hecto
 */
public class JDialogTarea extends javax.swing.JDialog {

    /**
     * Creates new form JDialogTarea
     */
    public JDialogTarea(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreCliente = new javax.swing.JTextField();
        lblDniCliente = new javax.swing.JLabel();
        txtDniCliente = new javax.swing.JTextField();
        lblTelefonoCliente = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        lblIsbnLibro = new javax.swing.JLabel();
        txtIsbnLibro = new javax.swing.JTextField();
        lblTituloLibro = new javax.swing.JLabel();
        txtTituloLibro = new javax.swing.JTextField();
        lblAutorLibro = new javax.swing.JLabel();
        txtAutorLibro = new javax.swing.JTextField();
        lblEditorialLibro = new javax.swing.JLabel();
        cmbEditorialLibro = new javax.swing.JComboBox<>();
        lblTipoEncuadernacion = new javax.swing.JLabel();
        cmbTipoEncuadernacion = new javax.swing.JComboBox<>();
        lblMaterias = new javax.swing.JLabel();
        tpnMaterias = new javax.swing.JTabbedPane();
        pnlAlimentacion = new javax.swing.JPanel();
        chbAnalisisAlimentos = new javax.swing.JCheckBox();
        chbIndustriaAlimentaria = new javax.swing.JCheckBox();
        chbNutricionDietetica = new javax.swing.JCheckBox();
        pnlMedicina = new javax.swing.JPanel();
        chbNeurologia = new javax.swing.JCheckBox();
        chbPatologia = new javax.swing.JCheckBox();
        chbMedicinaGeneral = new javax.swing.JCheckBox();
        pnlDerecho = new javax.swing.JPanel();
        chbDerechoPrivado = new javax.swing.JCheckBox();
        chbDerechoPublico = new javax.swing.JCheckBox();
        chbDerechoMilitar = new javax.swing.JCheckBox();
        pnlMusica = new javax.swing.JPanel();
        chbFlamenco = new javax.swing.JCheckBox();
        chbMusicaClasica = new javax.swing.JCheckBox();
        chbTeoriaHistoriaMusica = new javax.swing.JCheckBox();
        lblFechaPrestamoLibro = new javax.swing.JLabel();
        spnFechaEntregaLibro = new javax.swing.JSpinner();
        lblFechaEntregaLibro = new javax.swing.JLabel();
        spnFechaPrestamoLibro = new javax.swing.JSpinner();
        lblNombreCliente = new javax.swing.JLabel();
        Guardarbtn = new javax.swing.JButton();
        Salirbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNombreCliente.setToolTipText("Inserte nombre y apellidos");
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        lblDniCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDniCliente.setText("DNI");

        txtDniCliente.setToolTipText("Introduzca DNI");

        lblTelefonoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelefonoCliente.setText("Teléfono");

        txtTelefonoCliente.setToolTipText("Introduzca su teléfono");

        lblIsbnLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIsbnLibro.setText("ISBN");

        txtIsbnLibro.setToolTipText("Introduzca el ISBN del libro");

        lblTituloLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloLibro.setText("Título");

        txtTituloLibro.setToolTipText("Introduzca el título del libro");

        lblAutorLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAutorLibro.setText("Autor");

        txtAutorLibro.setToolTipText("Introduzca el autor del libro");

        lblEditorialLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditorialLibro.setText("Editorial");

        cmbEditorialLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urano Ediciones", "Círculo Rojo", "Vicens Vives", "Altamar" }));
        cmbEditorialLibro.setToolTipText("Elija la editorial del libro");
        cmbEditorialLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditorialLibroActionPerformed(evt);
            }
        });

        lblTipoEncuadernacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoEncuadernacion.setText("Tipo de Encuadernación");

        cmbTipoEncuadernacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rústica", "Tapa Dura", "Piel", " " }));
        cmbTipoEncuadernacion.setToolTipText("Elija el tipo de encuadernación ");
        cmbTipoEncuadernacion.setEnabled(false);

        lblMaterias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaterias.setText("Materias");

        tpnMaterias.setToolTipText("Escoja la materia ");

        chbAnalisisAlimentos.setText("Análisis de alimentos");
        pnlAlimentacion.add(chbAnalisisAlimentos);

        chbIndustriaAlimentaria.setText("Industria alimentaria");
        pnlAlimentacion.add(chbIndustriaAlimentaria);

        chbNutricionDietetica.setText("Nutrición y dietética");
        pnlAlimentacion.add(chbNutricionDietetica);

        tpnMaterias.addTab("Alimentacion-Nutrición", pnlAlimentacion);

        chbNeurologia.setText("Neurología");
        pnlMedicina.add(chbNeurologia);

        chbPatologia.setText("Patología");
        pnlMedicina.add(chbPatologia);

        chbMedicinaGeneral.setText("Medicina general");
        pnlMedicina.add(chbMedicinaGeneral);

        tpnMaterias.addTab("Medicina", pnlMedicina);

        chbDerechoPrivado.setText("Derecho privado");
        pnlDerecho.add(chbDerechoPrivado);

        chbDerechoPublico.setText("Derecho público");
        pnlDerecho.add(chbDerechoPublico);

        chbDerechoMilitar.setText("Derecho militar");
        pnlDerecho.add(chbDerechoMilitar);

        tpnMaterias.addTab("Derecho", pnlDerecho);

        chbFlamenco.setText("Flamenco");
        pnlMusica.add(chbFlamenco);

        chbMusicaClasica.setText("Música clásica");
        pnlMusica.add(chbMusicaClasica);

        chbTeoriaHistoriaMusica.setText("Teoría e historia de la música");
        pnlMusica.add(chbTeoriaHistoriaMusica);

        tpnMaterias.addTab("Música", pnlMusica);

        lblFechaPrestamoLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaPrestamoLibro.setText("Fecha Préstamo");

        spnFechaEntregaLibro.setModel(new javax.swing.SpinnerDateModel());
        spnFechaEntregaLibro.setToolTipText("Elija la fecha de devolución");

        lblFechaEntregaLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaEntregaLibro.setText("Fecha Entrega");

        spnFechaPrestamoLibro.setModel(new javax.swing.SpinnerDateModel());
        spnFechaPrestamoLibro.setToolTipText("Elija la fecha de préstamo");

        lblNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCliente.setText("NombreYApellidos");

        Guardarbtn.setToolTipText("Guardar todo el registro");
        Guardarbtn.setLabel("Guardar Registro");
        Guardarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarbtnActionPerformed(evt);
            }
        });

        Salirbtn.setText("Salir");
        Salirbtn.setToolTipText("Cerrar formulario");
        Salirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIsbnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(txtTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTipoEncuadernacion, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Guardarbtn)
                        .addGap(153, 153, 153)
                        .addComponent(Salirbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIsbnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaEntregaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaPrestamoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblEditorialLibro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(lblAutorLibro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnFechaPrestamoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnFechaEntregaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tpnMaterias)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbTipoEncuadernacion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbEditorialLibro, javax.swing.GroupLayout.Alignment.LEADING, 0, 237, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIsbnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditorialLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEditorialLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoEncuadernacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoEncuadernacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tpnMaterias)
                    .addComponent(lblMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnFechaPrestamoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaPrestamoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEntregaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnFechaEntregaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardarbtn)
                    .addComponent(Salirbtn))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarbtnActionPerformed
        String nombre = txtNombreCliente.getText().trim();
        String dni = txtDniCliente.getText().trim();
        String telefono = txtTelefonoCliente.getText().trim();
        String isbn = txtIsbnLibro.getText().trim();
        String titulo = txtTituloLibro.getText().trim();
        String autor = txtAutorLibro.getText().trim();

        // Validación básica
        if (nombre.isEmpty() || dni.isEmpty() || telefono.isEmpty() || isbn.isEmpty() || titulo.isEmpty() || autor.isEmpty() ||
            cmbEditorialLibro.getSelectedIndex() == 0 || cmbTipoEncuadernacion.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos correctamente.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "Registro guardado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Resetear la interfaz
        txtNombreCliente.setText("");
        txtDniCliente.setText("");
        txtTelefonoCliente.setText("");
        txtIsbnLibro.setText("");
        txtTituloLibro.setText("");
        txtAutorLibro.setText("");
        cmbEditorialLibro.setSelectedIndex(0);
        cmbTipoEncuadernacion.setSelectedIndex(0);
        spnFechaPrestamoLibro.setValue(new SpinnerDateModel().getValue());
        spnFechaEntregaLibro.setValue(new SpinnerDateModel().getValue());
    
    }//GEN-LAST:event_GuardarbtnActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void SalirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirbtnActionPerformed
        if (!txtNombreCliente.getText().trim().isEmpty() || !txtDniCliente.getText().trim().isEmpty() || !txtTelefonoCliente.getText().trim().isEmpty()) {

            int response = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres salir sin guardar los datos?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                dispose();
            }
        } else {
            dispose(); 
        }
    }//GEN-LAST:event_SalirbtnActionPerformed

    private void cmbEditorialLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditorialLibroActionPerformed

        String editorialSeleccionada = (String) cmbEditorialLibro.getSelectedItem();
                if ("Círculo Rojo".equals(editorialSeleccionada) || "Vicens Vives".equals(editorialSeleccionada)) {
                    cmbTipoEncuadernacion.setEnabled(true);
                } else {
                    cmbTipoEncuadernacion.setEnabled(false);
                }    }//GEN-LAST:event_cmbEditorialLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogTarea dialog = new JDialogTarea(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardarbtn;
    private javax.swing.JButton Salirbtn;
    private javax.swing.JCheckBox chbAnalisisAlimentos;
    private javax.swing.JCheckBox chbDerechoMilitar;
    private javax.swing.JCheckBox chbDerechoPrivado;
    private javax.swing.JCheckBox chbDerechoPublico;
    private javax.swing.JCheckBox chbFlamenco;
    private javax.swing.JCheckBox chbIndustriaAlimentaria;
    private javax.swing.JCheckBox chbMedicinaGeneral;
    private javax.swing.JCheckBox chbMusicaClasica;
    private javax.swing.JCheckBox chbNeurologia;
    private javax.swing.JCheckBox chbNutricionDietetica;
    private javax.swing.JCheckBox chbPatologia;
    private javax.swing.JCheckBox chbTeoriaHistoriaMusica;
    private javax.swing.JComboBox<String> cmbEditorialLibro;
    private javax.swing.JComboBox<String> cmbTipoEncuadernacion;
    private javax.swing.JLabel lblAutorLibro;
    private javax.swing.JLabel lblDniCliente;
    private javax.swing.JLabel lblEditorialLibro;
    private javax.swing.JLabel lblFechaEntregaLibro;
    private javax.swing.JLabel lblFechaPrestamoLibro;
    private javax.swing.JLabel lblIsbnLibro;
    private javax.swing.JLabel lblMaterias;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JLabel lblTipoEncuadernacion;
    private javax.swing.JLabel lblTituloLibro;
    private javax.swing.JPanel pnlAlimentacion;
    private javax.swing.JPanel pnlDerecho;
    private javax.swing.JPanel pnlMedicina;
    private javax.swing.JPanel pnlMusica;
    private javax.swing.JSpinner spnFechaEntregaLibro;
    private javax.swing.JSpinner spnFechaPrestamoLibro;
    private javax.swing.JTabbedPane tpnMaterias;
    private javax.swing.JTextField txtAutorLibro;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtIsbnLibro;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTituloLibro;
    // End of variables declaration//GEN-END:variables
}
